#!/bin/zsh

extensions=(".aux" ".fdb_latexmk" ".fls" ".asy" ".log" ".pre" ".synctex.gz" ".toc" ".glo" ".out" ".gls" ".ist" ".glg" ".dvi" ".out.ps" ".synctex(busy)")
files_array=($(ls))

for file in "${files_array[@]}"; do
    for ext in "${extensions[@]}"; do
        if [[ $file == *$ext ]]; then
            rm "$file"
        fi
    done
done
